server:
  port: 9120
spring:
  zipkin:
    base-url: http://localhost:9411/
#   Database Config
  datasource:
    url: jdbc:mysql://localhost:3306/business_micro?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#   Hibernate Config
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8081/eureka