server:
  port: 9110
spring:
  zipkin:
    base-url: http://localhost:9411/
  #DB config
  datasource:  
    url: jdbc:postgresql://localhost:5432/individual_micro
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  #Hibernate config
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8081/eureka