server:
  port: 9100
spring:
  zipkin:
    base-url: http://localhost:9411/
#   Database Config
  datasource:
    url: jdbc:postgresql://localhost:5432/user_micro
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
#   Hibernate Config
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8081/eureka